### ISSUE TITLE
Issues in Implementation of Authentication of users on Talent Acquisition Chatbot with SMS one time passcode.

### ISSUE THREAD

**Issue by charlie-2201** [IBM/authenticate-users-on-your-chatbot-with-sms-otp#13]
Issues in Implementation of Authentication of users on Talent Acquisition Chatbot with SMS one time passcode.
@jjasghar @christo4ferris @stevemar @maheshwarishikha @johnwalicki 
We have implemented the similar process as provided in the following link:
https://github.com/IBM/authenticate-users-on-your-chatbot-with-sms-otp

We have executed the same process for our Chatbot but when we executed over our own Skill then we faced these issues :
1. Content-Type HTTP header missing in callout response.

2. Connection to Webhook failed. No response.

3. SpelEvaluationException when evaluating dialog node ID [response_5_1641280674497]. The syntax of condition [$webhook_result_1.validPhoneNo == false] is valid, but cannot be evaluated. Check that objects in expression are not null or out of bounds.

4. SpEL evaluation error: Expression [$webhook_result_1.validPhoneNo == false] converted to [context['webhook_result_1'].validPhoneNo == false] at position 0: EL1007E: Property or field 'validPhoneNo' cannot be found on null

5. SpelEvaluationException when evaluating dialog node ID [response_4_1641280999048]. The syntax of condition [$webhook_result_10.authentication == false] is valid, but cannot be evaluated. Check that objects in expression are not null or out of bounds.

6. SpEL evaluation error: Expression [$webhook_result_10.authentication == false] converted to [context['webhook_result_10'].authentication == false] at position 0: EL1007E: Property or field 'authentication' cannot be found on null

7. SpelEvaluationException when evaluating dialog node ID [response_8_1641281226027]. The syntax of condition [$webhook_result_10.authentication == true] is valid, but cannot be evaluated. Check that objects in expression are not null or out of bounds.

8. SpEL evaluation error: Expression [$webhook_result_10.authentication == true] converted to [context['webhook_result_10'].authentication == true] at position 0: EL1007E: Property or field 'authentication' cannot be found on null

We have attached the .json Skill in zip format of our Chatbot as well as the source GitHub Skill for your reference along with the Screenshots of the errors.
![Screenshot (5)](https://user-images.githubusercontent.com/53409083/148037314-f485ce8a-ffb7-4ec2-8980-c4cd6e58f094.png)
![Screenshot (6)](https://user-images.githubusercontent.com/53409083/148037323-1d63e967-8706-4cfe-acee-84faa2dc1640.png)
![Screenshot (4)](https://user-images.githubusercontent.com/53409083/148037344-b45e6cf7-c4f0-4416-9577-ae5b4371cfde.png)
[skill-Digital-Horizons-HR-Chatbot.zip](https://github.com/IBM/authenticate-users-on-your-chatbot-with-sms-otp/files/7806617/skill-Digital-Horizons-HR-Chatbot.zip)
[skill-OTP-Authentication-New.zip](https://github.com/IBM/authenticate-users-on-your-chatbot-with-sms-otp/files/7806619/skill-OTP-Authentication-New.zip)

**Comment by jjasghar** [comment]
Hi! And thanks for the report. I'd strongly suggest getting @manojjahgirdar and/or @muralidharchavan to take a look at this because they were the original authors of this code.

Hopefully, they'll get back to you soon, and help you resolve this issue.

**Comment by muralidharchavan** [comment]
Hi @charlie-2201. Thanks for reaching out and thanks @jjasghar for redirecting the issue to me and @manojjahgirdar. 

@manojjahgirdar and I looked into the issue. At the outset, we think there could be configuration issue with webhook. Possibly it is best to have a quick screen sharing meeting and debug the issue. @charlie-2201, can you let me know a time when we can get into a 30 min meeting pls? We are in India timezone.

**Comment by charlie-2201** [comment]
@muralidharchavan  and @manojjahgirdar Thank you for your response and with the help of your suggestion we are able to solve the issue as I forgot to add .json in the end of Webhook link.
We are working on another project i.e. Online order processing during pandemics for Db2 connection with Watson Assistant.
We are facing the problem with the connection of Database.
Following are the errors:
  2022-01-05T13:58:03.72+0530 [HEALTH/0] ERR Failed to make TCP connection to port 8080: connection refused
   2022-01-05T13:58:03.72+0530 [CELL/0] ERR Failed after 1m3.784s: readiness health check never passed.

2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR   File "app.py", line 26, in <module>
   2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR     dsn_database = credentials1['db']
   2022-01-05T13:58:47.89+0530 [APP/PROC/WEB/0] ERR KeyError: 'db'

If its possible then can we have a meeting after 3:30 PM IST

**Comment by charlie-2201** [comment]
For the reference link:
https://github.com/IBM/online_order_processing_during_pandemics

**Comment by manojjahgirdar** [comment]
@charlie-2201 good to know that the issue has been resolved. 

For the Db2 connection code pattern can you verify if you have added the Db2 service credentials in the `ibm-db2-credentials.json` file?

**Comment by charlie-2201** [comment]
This the ibm-db2-credentials.json file
{
  "connection": {
    "cli": {
      "arguments": [
        [
          "-u",
          "tsl37238",
          "-p",
          "xeqAcUprLgNHr2u1",
          "--ssl",
          "--sslCAFile",
          "2ce1ab40-7379-45d8-a40c-38dcafaf95d0",
          "--authenticationDatabase",
          "admin",
          "--host",
          "b0aebb68-94fa-46ec-a1fc-1c999edb6187.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:31249"
        ]
      ],
      "bin": "db2",
      "certificate": {
        "certificate_base64": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFakNDQWZxZ0F3SUJBZ0lKQVA1S0R3ZTNCTkxiTUEwR0NTcUdTSWIzRFFFQkN3VUFNQjR4SERBYUJnTlYKQkFNTUUwbENUU0JEYkc5MVpDQkVZWFJoWW1GelpYTXdIaGNOTWpBd01qSTVNRFF5TVRBeVdoY05NekF3TWpJMgpNRFF5TVRBeVdqQWVNUnd3R2dZRFZRUUREQk5KUWswZ1EyeHZkV1FnUkdGMFlXSmhjMlZ6TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdXUvbitpWW9xdkdGNU8xSGpEalpsK25iYjE4UkR4ZGwKTzRUL3FoUGMxMTREY1FUK0plRXdhdG13aGljTGxaQnF2QWFMb1hrbmhqSVFOMG01L0x5YzdBY291VXNmSGR0QwpDVGcrSUsxbjBrdDMrTHM3d1dTakxqVE96N3M3MlZUSU5yYmx3cnRIRUlvM1JWTkV6SkNHYW5LSXdZMWZVSUtrCldNMlR0SDl5cnFsSGN0Z2pIUlFmRkVTRmlYaHJiODhSQmd0amIva0xtVGpCaTFBeEVadWNobWZ2QVRmNENOY3EKY21QcHNqdDBPTnI0YnhJMVRyUWxEemNiN1hMSFBrWW91SUprdnVzMUZvaTEySmRNM1MrK3labFZPMUZmZkU3bwpKMjhUdGJoZ3JGOGtIU0NMSkJvTTFSZ3FPZG9OVm5QOC9EOWZhamNNN0lWd2V4a0lSOTNKR1FJREFRQUJvMU13ClVUQWRCZ05WSFE0RUZnUVVlQ3JZanFJQzc1VUpxVmZEMDh1ZWdqeDZiUmN3SHdZRFZSMGpCQmd3Rm9BVWVDclkKanFJQzc1VUpxVmZEMDh1ZWdqeDZiUmN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQUkyRTBUOUt3MlN3RjJ2MXBqaHV4M0lkWWV2SGFVSkRMb0tPd0hSRnFSOHgxZ2dRcGVEcFBnMk5SCkx3R08yek85SWZUMmhLaWd1d2orWnJ5SGxxcHlxQ0pLOHJEU28xZUVPekIyWmE2S1YrQTVscEttMWdjV3VHYzMKK1UrVTFzTDdlUjd3ZFFuVjU0TVU4aERvNi9sVHRMRVB2Mnc3VlNPSlFDK013ejgrTFJMdjVHSW5BNlJySWNhKwozM0wxNnB4ZEttd1pLYThWcnBnMXJ3QzRnY3dlYUhYMUNEWE42K0JIbzhvWG5YWkh6UG91cldYS1BoaGdXZ2J5CkNDcUdIK0NWNnQ1eFg3b05NS3VNSUNqRVZndnNLWnRqeTQ5VW5iNVZZbHQ0b1J3dTFlbGdzRDNjekltbjlLREQKNHB1REFvYTZyMktZZE4xVkxuN3F3VG1TbDlTU05RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
        "name": "2ce1ab40-7379-45d8-a40c-38dcafaf95d0"
      },
      "composed": [
        "db2 -u tsl37238 -p xeqAcUprLgNHr2u1 --ssl --sslCAFile 2ce1ab40-7379-45d8-a40c-38dcafaf95d0 --authenticationDatabase admin --host b0aebb68-94fa-46ec-a1fc-1c999edb6187.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:31249"
      ],
      "environment": {},
      "type": "cli"
    },
    "db2": {
      "authentication": {
        "method": "direct",
        "password": "xeqAcUprLgNHr2u1",
        "username": "tsl37238"
      },
      "certificate": {
        "certificate_base64": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFakNDQWZxZ0F3SUJBZ0lKQVA1S0R3ZTNCTkxiTUEwR0NTcUdTSWIzRFFFQkN3VUFNQjR4SERBYUJnTlYKQkFNTUUwbENUU0JEYkc5MVpDQkVZWFJoWW1GelpYTXdIaGNOTWpBd01qSTVNRFF5TVRBeVdoY05NekF3TWpJMgpNRFF5TVRBeVdqQWVNUnd3R2dZRFZRUUREQk5KUWswZ1EyeHZkV1FnUkdGMFlXSmhjMlZ6TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdXUvbitpWW9xdkdGNU8xSGpEalpsK25iYjE4UkR4ZGwKTzRUL3FoUGMxMTREY1FUK0plRXdhdG13aGljTGxaQnF2QWFMb1hrbmhqSVFOMG01L0x5YzdBY291VXNmSGR0QwpDVGcrSUsxbjBrdDMrTHM3d1dTakxqVE96N3M3MlZUSU5yYmx3cnRIRUlvM1JWTkV6SkNHYW5LSXdZMWZVSUtrCldNMlR0SDl5cnFsSGN0Z2pIUlFmRkVTRmlYaHJiODhSQmd0amIva0xtVGpCaTFBeEVadWNobWZ2QVRmNENOY3EKY21QcHNqdDBPTnI0YnhJMVRyUWxEemNiN1hMSFBrWW91SUprdnVzMUZvaTEySmRNM1MrK3labFZPMUZmZkU3bwpKMjhUdGJoZ3JGOGtIU0NMSkJvTTFSZ3FPZG9OVm5QOC9EOWZhamNNN0lWd2V4a0lSOTNKR1FJREFRQUJvMU13ClVUQWRCZ05WSFE0RUZnUVVlQ3JZanFJQzc1VUpxVmZEMDh1ZWdqeDZiUmN3SHdZRFZSMGpCQmd3Rm9BVWVDclkKanFJQzc1VUpxVmZEMDh1ZWdqeDZiUmN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQUkyRTBUOUt3MlN3RjJ2MXBqaHV4M0lkWWV2SGFVSkRMb0tPd0hSRnFSOHgxZ2dRcGVEcFBnMk5SCkx3R08yek85SWZUMmhLaWd1d2orWnJ5SGxxcHlxQ0pLOHJEU28xZUVPekIyWmE2S1YrQTVscEttMWdjV3VHYzMKK1UrVTFzTDdlUjd3ZFFuVjU0TVU4aERvNi9sVHRMRVB2Mnc3VlNPSlFDK013ejgrTFJMdjVHSW5BNlJySWNhKwozM0wxNnB4ZEttd1pLYThWcnBnMXJ3QzRnY3dlYUhYMUNEWE42K0JIbzhvWG5YWkh6UG91cldYS1BoaGdXZ2J5CkNDcUdIK0NWNnQ1eFg3b05NS3VNSUNqRVZndnNLWnRqeTQ5VW5iNVZZbHQ0b1J3dTFlbGdzRDNjekltbjlLREQKNHB1REFvYTZyMktZZE4xVkxuN3F3VG1TbDlTU05RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
        "name": "2ce1ab40-7379-45d8-a40c-38dcafaf95d0"
      },
      "composed": [
        "db2://tsl37238:xeqAcUprLgNHr2u1@b0aebb68-94fa-46ec-a1fc-1c999edb6187.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:31249/bludb?authSource=admin&replicaSet=replset"
      ],
      "database": "bludb",
      "host_ros": [
        "b0aebb68-94fa-46ec-a1fc-1c999edb6187.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:30306"
      ],
      "hosts": [
        {
          "hostname": "b0aebb68-94fa-46ec-a1fc-1c999edb6187.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud",
          "port": 31249
        }
      ],
      "jdbc_url": [
        "jdbc:db2://b0aebb68-94fa-46ec-a1fc-1c999edb6187.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:31249/bludb:user=<userid>;password=<your_password>;sslConnection=true;"
      ],
      "path": "/bludb",
      "query_options": {
        "authSource": "admin",
        "replicaSet": "replset"
      },
      "replica_set": "replset",
      "scheme": "db2",
      "type": "uri"
    }
  },
  "instance_administration_api": {
    "deployment_id": "crn:v1:bluemix:public:dashdb-for-transactions:us-south:a/6161895d5a7a4264906608e687498909:880fdca7-da21-4d09-ab6c-35f28d8645da::",
    "instance_id": "crn:v1:bluemix:public:dashdb-for-transactions:us-south:a/6161895d5a7a4264906608e687498909:880fdca7-da21-4d09-ab6c-35f28d8645da::",
    "root": "https://api.db2.cloud.ibm.com/v5/ibm"
  }
}

**Comment by manojjahgirdar** [comment]
@charlie-2201 thanks for verifying. Don't post the actual credentials on GitHub it will be considered as a security breach, hence deleted it.

**Comment by manojjahgirdar** [comment]
@charlie-2201 I figured out what is causing the Db2 connection issue. I'm currently working on fixing it. I'll update you once fixed. Thanks.

**Comment by charlie-2201** [comment]
Have you completed the changes?
Thanks for listening

**Comment by manojjahgirdar** [comment]
@charlie-2201 Establish a new connection to an IBM Db2 server or database with `ibm_db` library has changed. Earlier one could connect to the Db without SSL certificate, however now SSL certificate is required to establish a connection with the Db. I'm working on changing the API implementations to authenticate with SSL.

**Comment by manojjahgirdar** [comment]
@charlie-2201 The Db2 instance on IBM Cloud is having some issues. I'm following up on the same. I'll get back to you as soon as possible. Thanks.

**Comment by manojjahgirdar** [comment]
@charlie-2201 The issue has been fixed. Please clone the repo once again to get the changes. Here is more details on the PR [#6](https://github.com/IBM/online_order_processing_during_pandemics/pull/6). Thanks.

**Comment by charlie-2201** [comment]
@manojjahgirdar The Issue has started again with the code 400 if it's possible for you to read it out then please let me know for the solution.
